// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

#ifndef PROTOBUF_packets_2eproto__INCLUDED
#define PROTOBUF_packets_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace packets {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_packets_2eproto();
void protobuf_AssignDesc_packets_2eproto();
void protobuf_ShutdownFile_packets_2eproto();

class Packet;
class Hello;
class Test;

enum ID {
  INVALID = 0,
  HELLO = 1,
  TEST = 2
};
bool ID_IsValid(int value);
const ID ID_MIN = INVALID;
const ID ID_MAX = TEST;
const int ID_ARRAYSIZE = ID_MAX + 1;

const ::google::protobuf::EnumDescriptor* ID_descriptor();
inline const ::std::string& ID_Name(ID value) {
  return ::google::protobuf::internal::NameOfEnum(
    ID_descriptor(), value);
}
inline bool ID_Parse(
    const ::std::string& name, ID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ID>(
    ID_descriptor(), name, value);
}
// ===================================================================

class Packet : public ::google::protobuf::Message {
 public:
  Packet();
  virtual ~Packet();

  Packet(const Packet& from);

  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Packet& default_instance();

  void Swap(Packet* other);

  // implements Message ----------------------------------------------

  Packet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Packet& from);
  void MergeFrom(const Packet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .packets.ID id = 1 [default = INVALID];
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::packets::ID id() const;
  inline void set_id(::packets::ID value);

  // @@protoc_insertion_point(class_scope:packets.Packet)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int id_;
  friend void  protobuf_AddDesc_packets_2eproto();
  friend void protobuf_AssignDesc_packets_2eproto();
  friend void protobuf_ShutdownFile_packets_2eproto();

  void InitAsDefaultInstance();
  static Packet* default_instance_;
};
// -------------------------------------------------------------------

class Hello : public ::google::protobuf::Message {
 public:
  Hello();
  virtual ~Hello();

  Hello(const Hello& from);

  inline Hello& operator=(const Hello& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Hello& default_instance();

  void Swap(Hello* other);

  // implements Message ----------------------------------------------

  Hello* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Hello& from);
  void MergeFrom(const Hello& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .packets.ID id = 1 [default = HELLO];
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::packets::ID id() const;
  inline void set_id(::packets::ID value);

  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:packets.Hello)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  int id_;
  friend void  protobuf_AddDesc_packets_2eproto();
  friend void protobuf_AssignDesc_packets_2eproto();
  friend void protobuf_ShutdownFile_packets_2eproto();

  void InitAsDefaultInstance();
  static Hello* default_instance_;
};
// -------------------------------------------------------------------

class Test : public ::google::protobuf::Message {
 public:
  Test();
  virtual ~Test();

  Test(const Test& from);

  inline Test& operator=(const Test& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Test& default_instance();

  void Swap(Test* other);

  // implements Message ----------------------------------------------

  Test* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Test& from);
  void MergeFrom(const Test& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .packets.ID id = 1 [default = TEST];
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::packets::ID id() const;
  inline void set_id(::packets::ID value);

  // required int32 some = 2;
  inline bool has_some() const;
  inline void clear_some();
  static const int kSomeFieldNumber = 2;
  inline ::google::protobuf::int32 some() const;
  inline void set_some(::google::protobuf::int32 value);

  // required string hello = 3;
  inline bool has_hello() const;
  inline void clear_hello();
  static const int kHelloFieldNumber = 3;
  inline const ::std::string& hello() const;
  inline void set_hello(const ::std::string& value);
  inline void set_hello(const char* value);
  inline void set_hello(const char* value, size_t size);
  inline ::std::string* mutable_hello();
  inline ::std::string* release_hello();
  inline void set_allocated_hello(::std::string* hello);

  // @@protoc_insertion_point(class_scope:packets.Test)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_some();
  inline void clear_has_some();
  inline void set_has_hello();
  inline void clear_has_hello();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int id_;
  ::google::protobuf::int32 some_;
  ::std::string* hello_;
  friend void  protobuf_AddDesc_packets_2eproto();
  friend void protobuf_AssignDesc_packets_2eproto();
  friend void protobuf_ShutdownFile_packets_2eproto();

  void InitAsDefaultInstance();
  static Test* default_instance_;
};
// ===================================================================


// ===================================================================

// Packet

// optional .packets.ID id = 1 [default = INVALID];
inline bool Packet::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Packet::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Packet::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Packet::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::packets::ID Packet::id() const {
  // @@protoc_insertion_point(field_get:packets.Packet.id)
  return static_cast< ::packets::ID >(id_);
}
inline void Packet::set_id(::packets::ID value) {
  assert(::packets::ID_IsValid(value));
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:packets.Packet.id)
}

// -------------------------------------------------------------------

// Hello

// optional .packets.ID id = 1 [default = HELLO];
inline bool Hello::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Hello::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Hello::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Hello::clear_id() {
  id_ = 1;
  clear_has_id();
}
inline ::packets::ID Hello::id() const {
  // @@protoc_insertion_point(field_get:packets.Hello.id)
  return static_cast< ::packets::ID >(id_);
}
inline void Hello::set_id(::packets::ID value) {
  assert(::packets::ID_IsValid(value));
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:packets.Hello.id)
}

// required string name = 2;
inline bool Hello::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Hello::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Hello::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Hello::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Hello::name() const {
  // @@protoc_insertion_point(field_get:packets.Hello.name)
  return *name_;
}
inline void Hello::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:packets.Hello.name)
}
inline void Hello::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:packets.Hello.name)
}
inline void Hello::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:packets.Hello.name)
}
inline ::std::string* Hello::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:packets.Hello.name)
  return name_;
}
inline ::std::string* Hello::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Hello::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:packets.Hello.name)
}

// -------------------------------------------------------------------

// Test

// optional .packets.ID id = 1 [default = TEST];
inline bool Test::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Test::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Test::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Test::clear_id() {
  id_ = 2;
  clear_has_id();
}
inline ::packets::ID Test::id() const {
  // @@protoc_insertion_point(field_get:packets.Test.id)
  return static_cast< ::packets::ID >(id_);
}
inline void Test::set_id(::packets::ID value) {
  assert(::packets::ID_IsValid(value));
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:packets.Test.id)
}

// required int32 some = 2;
inline bool Test::has_some() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Test::set_has_some() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Test::clear_has_some() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Test::clear_some() {
  some_ = 0;
  clear_has_some();
}
inline ::google::protobuf::int32 Test::some() const {
  // @@protoc_insertion_point(field_get:packets.Test.some)
  return some_;
}
inline void Test::set_some(::google::protobuf::int32 value) {
  set_has_some();
  some_ = value;
  // @@protoc_insertion_point(field_set:packets.Test.some)
}

// required string hello = 3;
inline bool Test::has_hello() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Test::set_has_hello() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Test::clear_has_hello() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Test::clear_hello() {
  if (hello_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    hello_->clear();
  }
  clear_has_hello();
}
inline const ::std::string& Test::hello() const {
  // @@protoc_insertion_point(field_get:packets.Test.hello)
  return *hello_;
}
inline void Test::set_hello(const ::std::string& value) {
  set_has_hello();
  if (hello_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    hello_ = new ::std::string;
  }
  hello_->assign(value);
  // @@protoc_insertion_point(field_set:packets.Test.hello)
}
inline void Test::set_hello(const char* value) {
  set_has_hello();
  if (hello_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    hello_ = new ::std::string;
  }
  hello_->assign(value);
  // @@protoc_insertion_point(field_set_char:packets.Test.hello)
}
inline void Test::set_hello(const char* value, size_t size) {
  set_has_hello();
  if (hello_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    hello_ = new ::std::string;
  }
  hello_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:packets.Test.hello)
}
inline ::std::string* Test::mutable_hello() {
  set_has_hello();
  if (hello_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    hello_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:packets.Test.hello)
  return hello_;
}
inline ::std::string* Test::release_hello() {
  clear_has_hello();
  if (hello_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = hello_;
    hello_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Test::set_allocated_hello(::std::string* hello) {
  if (hello_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete hello_;
  }
  if (hello) {
    set_has_hello();
    hello_ = hello;
  } else {
    clear_has_hello();
    hello_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:packets.Test.hello)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace packets

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::packets::ID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::packets::ID>() {
  return ::packets::ID_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_packets_2eproto__INCLUDED
